plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'maven-publish'
}

group 'FireMysteryBlocks'
version = "2.3.13"

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

dependencies {
//    implementation project(":API")
//    implementation fileTree("archive")

    // Server jars
    compileOnly "net.minecraft:server:1.18.1"
    compileOnly "org.spigotmc:v1_18_R2:b3450-2"
    //compileOnly "net.minecraft:server:1.8"
    //compileOnly "org.spigotmc:v1_8_R1:latest"

    // Addons
    compileOnly "me.clip:placeholderapi:2.10.9"
    compileOnly "com.zrips:cmi:9.2.6.1"
    compileOnly "com.zrips:cmiLib:1.2.3.7"
    compileOnly "com.gmail.filoghost.holographicdisplays:HolographicDisplays:2.4.9"
    compileOnly 'com.github.decentsoftware-eu:decentholograms:2.8.3'

    // Implementations
    implementation "com.iridium:IridiumColorAPI:1.0.5"
    implementation 'com.zaxxer:HikariCP:4.0.3'
    implementation 'de.tr7zw:item-nbt-api:2.13.2'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'com.github.johnrengelman.shadow'

    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url = 'https://repo.codemc.io/repository/maven-public' }
        maven { url = 'https://repo.bg-software.com/repository/nms/' }

        maven {
            url 'http://nexus.basicland.cz:8081/repository/dev-nms/'
            allowInsecureProtocol = true
        }
        maven {
            url 'http://nexus.basicland.cz:8081/repository/dev-public/'
            allowInsecureProtocol = true
        }
        maven {
            url 'http://nexus.basicland.cz:8081/repository/dev-private/'
            credentials {
                username "admin"
                password "brokolice"
            }
            allowInsecureProtocol = true
        }
    }

    dependencies {
        // Annotation
        compileOnly 'org.jetbrains:annotations:24.0.0'
        compileOnly 'org.projectlombok:lombok:1.18.26'
        annotationProcessor 'org.projectlombok:lombok:1.18.26'
    }

    build {
        dependsOn shadowJar
    }
}

subprojects {
    shadowJar {
        // Relocate
//        relocate 'de.tr7zw.changeme.nbtapi', 'cz.devfire.mysteryblocks.nbtapi'

        archiveFileName = "${project.group}-${project.name}-${rootProject.version}.jar"
        destinationDirectory = file("../target/${rootProject.version}")
    }
}

shadowJar {
    dependsOn(jar)

    delete fileTree("./target/") {
        exclude archiveFileName.get()
    }

    // Relocate
    relocate 'de.tr7zw.changeme.nbtapi', 'cz.devfire.mysteryblocks.nbtapi'

    archiveFileName = "${project.name}-${project.version}.jar"
    archiveClassifier.set("")
    destinationDirectory = file("target/${rootProject.version}")
}

processResources {
    outputs.upToDateWhen { false }

    eachFile { details ->
        if (details.name.contentEquals('plugin.yml') || details.name.contentEquals('bungee.yml')) {
            filter { String line ->
                line.replace('${project.version}', (String) version)
            }
        }
    }
}

build {
    dependsOn clean
    dependsOn shadowJar
}

publish.shouldRunAfter shadowJar